package pwo.group.app.gui;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;
import pwo.group.app.core.CollectionBuilder;
import pwo.group.app.fileops.FileComparisonService;
import pwo.group.app.fileops.FileStatisticService;
import pwo.group.app.fileops.FileWithStats;

/**
 *
 * @author Bohdan Basistyi
 */
public class CompareFilesForm extends javax.swing.JFrame {

    public CompareFilesForm() {
        initComponents();
    }
    
    /**
     * Creates new form CompareFilesForm
     */
    public CompareFilesForm(String filePath1, String filePath2) {
        initComponents();
        
        var statisticService = new FileStatisticService();
        var file1Stats = statisticService.GetFileStatistics(filePath1);
        var file2Stats = statisticService.GetFileStatistics(filePath2);
        
        var file1 = new FileWithStats(filePath1, file1Stats);
        var file2 = new FileWithStats(filePath2, file2Stats);
        
        var fileComparisonService = new FileComparisonService();
        var filesWithCommonOnly = fileComparisonService.TrimNonCommonProperties(new ArrayList<>(Arrays.asList(file1, file2)));
        
        var columns = Stream.concat(Stream.of("Property"), filesWithCommonOnly.stream().map(file -> file.GetFilePath())).toArray(String[]::new);
        
        var data = filesWithCommonOnly.get(0).GetStats().stream()
                .map(prop -> CollectionBuilder.fromCollection(new ArrayList<String>())
                        .add(prop.GetName())
                        .addAll(filesWithCommonOnly.stream()
                                .map(file -> file.GetStats().stream()
                                        .filter(stat -> stat.getClass() == prop.getClass())
                                        .findFirst().get().GetValue().toString())
                                .collect(java.util.stream.Collectors.toCollection(ArrayList::new))
                        )
                        .build()
                )
                .collect(java.util.stream.Collectors.toCollection(ArrayList::new))
                .stream()
                .map(list -> list.toArray(String[]::new))
                .toArray(String[][]::new);
        
        DefaultTableModel model = new DefaultTableModel(data, columns);
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompareFilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompareFilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompareFilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompareFilesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompareFilesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
